done fixes in settings and changed privacy url
TrustNetPK/cov-id-wallet pull request #47
Opened 2020-09-05 11:22 UTC by khuzama98

2020-09-05 15:24 UTC, osancus requested changes
I believe you don't have prettier installed on your VSCode or you are not using VSCode. The code is reformated which makes unnecessary changes to code. Can you please fix that, see .prettierrc.js file.

2020-09-05 15:26 UTC, osancus commented on covidWallet/app/screens/SettingsScreen.js
>        value: 'Iphone',
Change this to 'Phone'

2020-09-05 15:27 UTC, osancus commented on covidWallet/app/screens/SettingsScreen.js
>        value: 'Soverin Staging Network',
Change this to 'BCovrin Test Network'

2020-09-09 20:26 UTC, osancus requested changes
This is how the image looks on iOS. Can you please make sure that the back button is transparent and the setting is not so top screen aligned but instead at a significant distance from the list below. Thank you!

![IMG_197BF9D20411-1](https://user-images.githubusercontent.com/6899072/92649204-55485580-f2f3-11ea-991a-f80c589c9a76.jpeg)

2020-09-10 14:20 UTC, khuzama98 commented
@osancus I have done the changes again please review it and let me know, Thanks.

2020-09-10 19:34 UTC, osancus approved these changes

2020-09-10 19:34 UTC, merged